# syntax=docker/dockerfile:1.6
FROM maven:3-eclipse-temurin-17 AS builder

WORKDIR /src
COPY --link pom.xml .

WORKDIR /src/test-coverage
COPY --link ./test-coverage/pom.xml .

WORKDIR /src/apps
COPY --link ./apps/pom.xml .

WORKDIR /src/apps/user-cdc
COPY --link ./apps/user-cdc/pom.xml .
COPY ./apps/user-cdc/src/main/ ./src/main/

RUN echo "<servers>\n" \
		 "<server>\n" \
		 "<id>$repositoryId</id>\n" \
		 "<username>$repoLogin</username>\n" \
		 "<password>$repoPwd</password>\n" \
		 "</server>\n" \
		 "</servers>\n" > settings.xml

ARG REPO_ID
ARG REPO_USERNAME
ARG REPO_PASSWORD
ENV REPO_ID=${REPO_ID} REPO_USERNAME=${REPO_USERNAME} REPO_PASSWORD=${REPO_PASSWORD}

RUN mvn --global-settings settings.xml --projects :user-cdc -DrepositoryId=${REPO_ID} -DrepoLogin=${REPO_USERNAME} -DrepoPwd=${REPO_PASSWORD} --also-make clean package -DskipTests

FROM openjdk:17-jdk AS runtime

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

WORKDIR /app

COPY --from=builder /src/apps/user-cdc/target/quarkus-app/lib/ ./lib/
COPY --from=builder /src/apps/user-cdc/target/quarkus-app/*.jar ./
COPY --from=builder /src/apps/user-cdc/target/quarkus-app/app/ ./app/
COPY --from=builder /src/apps/user-cdc/target/quarkus-app/quarkus/ ./quarkus/

EXPOSE 8080
USER 1001

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTIONS -jar /app/quarkus-run.jar"]
