version: '3.8'
services:

  mongodb:
    image: mongo:latest@sha256:f6164e498dbaee3966031c1ced1bfa0fd1c4961151b38a770fa6994f4b0dcae7
    ports:
      - '27017:27017'
    networks:
      - develop-network

networks:
  develop-network:
    name: selfcare-develop-network