version: '3.8'
services:

  mongodb:
    image: mongo:latest@sha256:aaad67f2dca93148e5343c03210bcfc89a0107516a4756bfa018acd6579e5b18
    ports:
      - '27017:27017'
    networks:
      - develop-network

networks:
  develop-network:
    name: selfcare-develop-network