name: "Integration Tests (user-ms)"

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - releases/*
    paths:
      - "apps/user-ms/**"
      - ".github/workflows/integration_tests_ms.yml"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch su cui eseguire i test di integrazione'
        required: true
        default: 'main'

jobs:
  integration_tests_ms:
    name: 'Integration Tests (user-ms)'
    runs-on: ubuntu-24.04

    steps:
      - name: Set missing library
        run: |
          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: 'temurin'
          maven-version: '3.9.5'
          cache-enabled: true
          checkout-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event.inputs.branch }}

      - uses: s4u/maven-settings-action@60912582505985be4cc55d2b890eb32767f8de5f # pin@v2.8.0
        with:
          servers: '[{"id": "selfcare-onboarding", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}, {"id": "selfcare", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

      - name: Run Integration Tests
        run: mvn --projects :user-ms --also-make test -Dtest=CucumberSuite -Dsurefire.failIfNoSpecifiedTests=false
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: apps/user-ms/target/cucumber-report/cucumber.html
