name: "Integration Tests (user-ms)"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - releases/*
    paths:
      - "apps/user-ms/**"

jobs:
  integration_tests_ms:
    name: 'Integration Tests (user-ms)'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: 'temurin'
          maven-version: '3.9.5'
          cache-enabled: true

      - uses: s4u/maven-settings-action@60912582505985be4cc55d2b890eb32767f8de5f # pin@v2.8.0
        with:
          servers: '[{"id": "selfcare-onboarding", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

      - name: Run Integration Tests
        working-directory: apps/user-ms
        run: mvn -U test -Dtest=it.pagopa.selfcare.user.integration_test.CucumberSuite
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
