name: Deploy PNPG - user-cdc

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "apps/user-cdc/**"
      - "infra/container_apps/user-cdc/**"
      - "apps/pom.xml"
      - "pom.xml"
  
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Dev] PNPG User cdc Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-pnpg
      dir: 'infra/container_apps/user-cdc'
      dockerfile_path: ./apps/user-cdc/Dockerfile
      docker_image_name: pagopa/selfcare-user-cdc

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[UAT] PNPG User cdc Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat-pnpg
      dir: 'infra/container_apps/user-cdc'
      dockerfile_path: ./apps/user-cdc/Dockerfile
      docker_image_name: pagopa/selfcare-user-cdc

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Prod] PNPG User cdc Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod-pnpg
      dir: 'infra/container_apps/user-cdc'
      dockerfile_path: ./apps/user-cdc/Dockerfile
      docker_image_name: pagopa/selfcare-user-cdc
